[package]
org = "ballerinax"
name = "vimeo"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
license = ["Apache-2.0"]
keywords = ["vimeo", "media"]

[build-options]
observabilityIncluded = true
