[package]
license = ["Apache-2.0"]
keywords = ["AI/Images", "OpenAI", "Cost/Paid", "generation", "DALL-E 2", "Vendor/OpenAI"]
org = "ballerinax"
name = "openai.images"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/openai.images"
version = "1.0.6"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
