[package]
license = ["Apache-2.0"]
keywords = ["sap", "saps4hana", "promotion", "paid"]
org = "ballerinax"
name = "saps4hana.itcm.promotion"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
