[package]
license = ["Apache-2.0"]
keywords = ["AI/Audio", "OpenAI", "Cost/Paid", "speech-to-text", "Whisper", "Vendor/OpenAI"]
org = "ballerinax"
name = "openai.audio"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/openai.audio"
version = "1.0.6"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
