[package]
license = ["Apache-2.0"]
keywords = ["zendesk", "customer service", "ticket", "freemium"]
org = "ballerinax"
name = "zendesk.support"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
