name: Daily build

# Controls when the action will run.
on: 
  schedule:
    - cron: '30 2 * * *'

jobs:
  dailyBuild:
    runs-on: ubuntu-latest
    container:
      image: ballerina/ballerina:nightly
      options: --user root
    steps:
      - uses: actions/checkout@v1   
      - name: Build with Gradle
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
          GRADLE_USER_HOME: ~/.gradle
        run: |
          ./gradlew build -Prelease=false -Premote=true -Ppublishing=false
      # Send notification when build fails
      - name: Notify failure
        if: ${{ failure() }}
        run: |
          curl \
          -X POST 'https://chat.googleapis.com/v1/spaces/${{secrets.BALLERINA_CHAT_ID}}/messages?key=${{secrets.BALLERINA_CHAT_KEY}}&token=${{secrets.BALLERINA_CHAT_TOKEN}}' \
          --header 'Content-Type: application/json' \
          -d '{"text": "*openapi-connectors* daily build failure \nPlease visit <https://github.com/ballerina-platform/ballerinax-openapi-connectors/actions/workflows/daily-build.yml|the daily build page> for more information"}'
          curl \
          -X POST 'https://chat.googleapis.com/v1/spaces/${{secrets.CONNECTOR_CHAT_ID}}/messages?key=${{secrets.CONNECTOR_CHAT_KEY}}&token=${{secrets.CONNECTOR_CHAT_TOKEN}}' \
          --header 'Content-Type: application/json' \
          -d '{"text": "*openapi-connectors* daily build failure \nPlease visit <https://github.com/ballerina-platform/ballerinax-openapi-connectors/actions/workflows/daily-build.yml|the daily build page> for more information"}'
