name: Regenerate Connectors

on:
  # # Run nightly at 2:00 AM
  # schedule:
  #   - cron: '0 2 * * *'
  # Trigger manually with specified Ballerina Docker version
  workflow_dispatch:
    inputs:
      bal_docker_version:
        description: Ballerina Docker version
        required: true
        default: 'nightly'
      client_method:
        description: Expected Client Method Type
        required: true
        default: 'remote'
        options: ['remote', 'resource']
      custom_distribution_path:
        description: Path to Ballerina Custom Distribution
        required: false
        default: ''


jobs:
  # regenerate_connectors_with_nightly:
  #   if: github.event_name == 'schedule'
  #   runs-on: ubuntu-latest
  #   container:
  #     image: ballerina/ballerina:nightly
  #     options: --user root
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
      
  #     - name: Build with Gradle
  #       env:
  #         JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
  #         GRADLE_USER_HOME: ~/.gradle
  #       run: |
  #         ./gradlew build -PtestConnectorGeneration=true -PclientMethod=${{ github.event.inputs.client_method }}

  regenerate_connectors_with_specified_version:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    container:
      image: ballerina/ballerina:${{ github.event.inputs.bal_docker_version }}
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: Set up JDK 17
      #   uses: actions/setup-java@v2
      #   with:
      #     distribution: 'adopt'
      #     java-version: 17
      - name: Download and Unzip
        if: github.event.inputs.custom_distribution_path != ''
        run: |
          wget --header="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -O ballerina.zip "${{ github.event.inputs.custom_distribution_path }}/zip"
          unzip -o ballerina.zip
          balDistZip=$(find . -name 'ballerina-*.zip' | head -n 1)
          echo "Unzipping ${balDistZip}"
          unzip -o "${balDistZip}"
          EXTRACTED_DISTRIBUTION_PATH="${balDistZip%.zip}"
          export EXTRACTED_DISTRIBUTION_PATH="${balDistZip%.zip}"
          echo $EXTRACTED_DISTRIBUTION_PATH
          # echo "::set-env name=EXTRACTED_DISTRIBUTION_PATH::$EXTRACTED_DISTRIBUTION_PATH"

      - name: Build with Gradle
        env:
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
          GRADLE_USER_HOME: ~/.gradle
        run: |
          ./gradlew build -PtestConnectorGeneration=true -PclientMethod=${{ github.event.inputs.client_method }}
      - name: Upload Summary Report
        uses: actions/upload-artifact@v2
        with:
          name: summary-report
          path: .github/reports/summary.txt
